version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ORGANISATION_ID=${ORGANISATION_ID}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - PORT=8080
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - dalle-network
    restart: unless-stopped
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - VITE_SERVER_URL=http://server:8080
    networks:
      - dalle-network
    restart: unless-stopped

networks:
  dalle-network:
    driver: bridge 